language: node_js

node_js:
  - 12.7.0

install:
  - npm install -g typescript
  - npm install

script:
  - npm run lint

deploy:
  provider: npm
  edge: true
  email: chame1eon@protonmail.com
  api_key:
    secure: wanaKWcaTuq7X3q9ckqNzwViZD0tvRTtpGdwlHI/vLB4gn3I+Ekmq8eRF4RLjRiCKmBKn2Lb9Fbphmtbo4dihSwqqkVwxpnDX2mkv6wwIusDNKqPLxis5E0aviN+gSldMUmqEXP9TdqP6p/Omz99DYHHcArrQC5G6PBnRNZem/G7FIySWvi42FbGA2/SvH4n+lIsyOEx/qSCb22mMe340fsr1wVBGqSPy0r3yCltMvzSxuOZE27yDFcW4foIwovlq99oZcB5ppPufLbP6WdaCovyTdtq7dbyMawR8xIw9svjt+iGCmpOr+aTKZwT6HahHCl0uBoRMZyd1Jb8E8ZA6NRhDhiJdBM48Rx8Z42PFRQGkh0phxotezqCXL4XWJAfkGB6jeY9A/nC3I1BNJWJ01Wq5OLflxxAHeMKt1gm5lVYyJwvZs3tTVbj1nnySP42w6bmtt5DBzjhEimj/JmDgRitg0LyFvAg3t8TZPJPdaV8o9J1c6VPBbW+KuPfgPOZVHdCK7WjHrW9MCLBkEMnElB3HApzZdrPJfBRLyBBWoG9AmFNzrTRN3+8RH+4QOVphNEUkvk7r0ME2383+IC4WPEnXbU9p2DWdU5ZXKfGBfpBipmiIDJ4WxMcTc3jei9paGCbInASNH56M4IcCi8MLkqNLcpOg4ZN6arvV4vMX20=
  cleanup: true
  on:
    tags: true
